[View in Colaboratory](https://colab.research.google.com/github/RayleighKim/M07_Numpy-Pandas_with_google_colab/blob/master/72_Pandas.ipynb)

# 72 Pandas

Editor : Rayleigh Kim

email : rayleigh@dplus.company

thanks to 이숙번 님

이 노트북의 70%는 숙번님께서 제작하셨습니다.


#### 주의 : 판다스의 모든 것을 다루지 않습니다. Machine Learning 또는 Deep Learning을 공부하기 위해 최소한 알아야 하는 범위만을 다룹니다.


### 파이썬 실습시간!

pandas 데이터 분석 라이브러리의 사용법을 간략하게 설명합니다.
데이터의 로드, 파싱 및 변환을 위한 방법을 보여줍니다.

#### 선행지식
1. Python 언어 기초.
2. Numpy 라이브러리 기초.
3. table 구조의 데이터에 대한 이해. (엑셀 형태의 데이터)

#### 실습목표
1. csv 파일 읽는법. 
2. dataframe을 만드는 법.
2. dataframe을 다루기.
3. head, tail
4. 정렬
5. numpy array와 변환, 
6. 다양한 dataframe 연산.


## 00. 라이브러리 불러오기 & 데이터 업로드

In [0]:
import pandas as pd
from google.colab import files

In [4]:
uploaded = files.upload() # Graduate_apply.csv를 업로드 해두자

Saving Graduate_apply.csv to Graduate_apply.csv


In [5]:
ls

Graduate_apply (1).csv  Graduate_apply.csv
Graduate_apply (2).csv  sample_data/


## 01. Creating Data Frames

In [0]:
# Dataframes 생성
d = {
   'col1': ['Item0', 'Item0', 'Item1', 'Item1'],
   'col2': ['Gold', 'Bronze', 'Gold', 'Silver'],
   'col3': [1, 2, 3, 4]
}
df = pd.DataFrame(d)

In [7]:
# Numpy Array => Pandas DataFrame
import numpy as np

dates = pd.date_range('20171201', periods=6)
# DatetimeIndex(['2017-12-01', '2017-12-02', '2017-12-03', '2017-12-04',
#                '2017-12-05', '2017-12-06'],
#               dtype='datetime64[ns]', freq='D')

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
#                   A         B         C         D
# 2013-01-01  0.469112 -0.282863 -1.509059 -1.135632
# 2013-01-02  1.212112 -0.173215  0.119209 -1.044236
# 2013-01-03 -0.861849 -2.104569 -0.494929  1.071804
# 2013-01-04  0.721555 -0.706771 -1.039575  0.271860
# 2013-01-05 -0.424972  0.567020  0.276232 -1.087401
# 2013-01-06 -0.673690  0.113648 -1.478427  0.524988

df

A         B         C         D
2017-12-01 -0.875593  1.057400 -0.082805  2.077097
2017-12-02 -1.351431 -0.312819 -0.554388 -0.626229
2017-12-03  0.474928  1.553974  0.033526 -1.445241
2017-12-04 -1.041249 -0.751877 -0.368256  0.514139
2017-12-05 -0.375617  1.141626 -1.942709 -0.121088
2017-12-06 -1.610864 -0.568005  0.697468  0.796999

In [8]:
# Pandas DataFrame => Numpy Array
np_array = df.values
print(np_array, np_array.shape)

[[-0.87559316  1.05739976 -0.08280529  2.07709689]
 [-1.35143068 -0.3128186  -0.55438814 -0.62622928]
 [ 0.47492755  1.55397403  0.03352623 -1.44524119]
 [-1.04124939 -0.75187696 -0.36825634  0.51413936]
 [-0.37561687  1.14162604 -1.94270933 -0.12108764]
 [-1.61086421 -0.56800525  0.69746818  0.79699895]] (6, 4)


In [10]:
# Loading CSV files

df = pd.read_csv('./Graduate_apply.csv', sep=',')
print(df.head())

df = pd.read_csv('./Graduate_apply.csv', sep=',', skipinitialspace=True)
print(df.head())

# to_csv
df.to_csv('./file.csv', header=True, index=False, encoding='utf-8')

   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4
   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4


In [11]:
ls

file.csv                Graduate_apply (2).csv  sample_data/
Graduate_apply (1).csv  Graduate_apply.csv


## 02. Previewing Data

In [12]:
# 첫 5개 행의 데이터를 보여줍니다.
df.head()

admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

In [13]:
# 마지막 3개 행의 데이터를 보여줍니다.
df.tail(3)

admit  gre   gpa  rank
397      0  460  2.63     2
398      0  700  3.65     2
399      0  600  3.89     3

In [14]:
# 데이터 프레임 모양 확인 - (rows, cols) tuple
df.shape

(400, 4)

In [16]:
# 칼럼명 출력
print(df.columns)
print(list(df))

Index(['admit', 'gre', 'gpa', 'rank'], dtype='object')
['admit', 'gre', 'gpa', 'rank']


In [17]:
# 각 칼럼의 데이터 타입
df.dtypes

admit      int64
gre        int64
gpa      float64
rank       int64
dtype: object

In [18]:
# 데이터 출력 - numpy array
df.values

array([[  0.  , 380.  ,   3.61,   3.  ],
       [  1.  , 660.  ,   3.67,   3.  ],
       [  1.  , 800.  ,   4.  ,   1.  ],
       ...,
       [  0.  , 460.  ,   2.63,   2.  ],
       [  0.  , 700.  ,   3.65,   2.  ],
       [  0.  , 600.  ,   3.89,   3.  ]])

In [19]:
# 간단한 통계 정보
df.describe()

admit         gre         gpa       rank
count  400.000000  400.000000  400.000000  400.00000
mean     0.317500  587.700000    3.389900    2.48500
std      0.466087  115.516536    0.380567    0.94446
min      0.000000  220.000000    2.260000    1.00000
25%      0.000000  520.000000    3.130000    2.00000
50%      0.000000  580.000000    3.395000    2.00000
75%      1.000000  660.000000    3.670000    3.00000
max      1.000000  800.000000    4.000000    4.00000

## 03. Sorting

In [20]:
# index로 정렬
df.sort_index(axis=0, ascending=False).head()

admit  gre   gpa  rank
399      0  600  3.89     3
398      0  700  3.65     2
397      0  460  2.63     2
396      0  560  3.04     3
395      0  620  4.00     2

In [21]:
# 특정 컬럼의 값으로 정렬
df.sort_values(by=['admit', 'gpa'], ascending=False).head()

admit  gre  gpa  rank
2       1  800  4.0     1
12      1  760  4.0     1
14      1  700  4.0     1
33      1  800  4.0     3
55      1  740  4.0     3

### 실습

In [0]:
# pandas 라이브러리 호출

# pandas read_csv 함수를 이용하여 ./resources/graduate_apply.csv 파일을 읽고, data_frame 변수에 담습니다. 

# data_frame의 shape를 확인합니다.

# data_frame의 칼럼명과 각 칼럼의 데이터 타입을 확인합니다.

# data_frame의 데이터의 첫 3행의 데이터와 마지막 3행의 데이터를 출력합니다.

# data_frame의 데이터를 numpy array로 변환하여 출력합니다.

# data_frame의 데이터를 'gra' 칼럼을 기준으로 오름차순으로 정렬합니다. 


## 04. Selecting/Querying

In [22]:
# 칼럼명으로 조회 1
df.gre.head()

0    380
1    660
2    800
3    640
4    520
Name: gre, dtype: int64

In [23]:
# 칼럼명으로 조회 2
df['gre'].head()
df['gre'].unique()          # 중복 제거

array([380, 660, 800, 640, 520, 760, 560, 400, 540, 700, 440, 480, 780,
       360, 500, 600, 680, 620, 580, 460, 740, 300, 720, 340, 420, 220])

In [24]:
# 두 개의 칼럼 동시 조회
df[['gpa', 'gre']].head()

gpa  gre
0  3.61  380
1  3.67  660
2  4.00  800
3  3.19  640
4  2.93  520

In [25]:
# 행번호 1 조회
df.iloc[1]

admit      1.00
gre      660.00
gpa        3.67
rank       3.00
Name: 1, dtype: float64

In [26]:
# 행번호 1~3 조회
df.iloc[1:3]

admit  gre   gpa  rank
1      1  660  3.67     3
2      1  800  4.00     1

In [27]:
# 0번째 row, 0번째 column
df.iloc[0, 0]

0

In [28]:
# 0~4 rows & 0~2 columns
df.iloc[0:4, 0:2]

admit  gre
0      0  380
1      1  660
2      1  800
3      1  640

In [29]:
# Produces and array, not a single value!
(df.gpa > 3.5).head()

0     True
1     True
2     True
3    False
4    False
Name: gpa, dtype: bool

In [30]:
# Query by a single column value
df[df.gpa > 3.0].head()

admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
7      0  400  3.08     2

In [31]:
# Query by a single column, if it is in a list of predefined values
df[df['rank'].isin([1, 2])].head()

admit  gre   gpa  rank
2      1  800  4.00     1
5      1  760  3.00     2
6      1  560  2.98     1
7      0  400  3.08     2
9      0  700  3.92     2

In [32]:
# A conjunction query using two columns
df[(df['gpa'] > 3.0) & (df['rank'] == 3)].head()

admit  gre   gpa  rank
0       0  380  3.61     3
1       1  660  3.67     3
8       1  540  3.39     3
15      0  480  3.44     3
20      0  500  3.17     3

In [33]:
# A disjunction query using two columns
df[(df['gpa'] > 3.0) | (df['rank'] == 3)].head()

admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
7      0  400  3.08     2

In [34]:
# Dataframes 생성
d = {
   'col1': ['Item0', 'Item0', 'Item1', 'Item1'],
   'col2': ['Gold', 'Bronze', 'Gold', 'Silver'],
   'col3': [1, 2, 3, 4]
}
df1 = pd.DataFrame(d)

# 문자열이 들어있는 row만 조회
df1[df1.col2.str.contains('ilver')]

col1    col2  col3
3  Item1  Silver     4

### 실습

In [0]:
# pandas 라이브러리 호출

# pandas read_csv 함수를 이용하여 ./resources/graduate_apply.csv 파일을 읽고, data_frame 변수에 담습니다. 

# data_frame의 shape를 확인합니다.

# data_frame의 칼럼명과 각 칼럼의 데이터 타입을 확인합니다.

# data_frame의 데이터의 첫 3행의 데이터와 마지막 3행의 데이터를 출력합니다.

# 'gpa' 칼럼의 데이터를 조회합니다. 

# unique 함수를 가지고 'rank'의 칼럼에 들어있는 데이터의 종류를 확인합니다.

# 100번째 행의 데이터를 조회합니다.

# rank가 0인 데이터를 조회합니다. 

# rank가 3, 4인 데이터의 갯수를 확인합니다.


## 05. Modifying Data Frames

In [35]:
# 인덱스와 칼럼명으로 조회 & 수정
df1.loc[1, 'col2'] = 'Bronze and Gold' 
df1

col1             col2  col3
0  Item0             Gold     1
1  Item0  Bronze and Gold     2
2  Item1             Gold     3
3  Item1           Silver     4

In [36]:
# 행번호, 열번호로 조회 & 수정
df1.iloc[1, 1] = 'Bronze again' 
df1

col1          col2  col3
0  Item0          Gold     1
1  Item0  Bronze again     2
2  Item1          Gold     3
3  Item1        Silver     4

In [37]:
# Replaces the column with the array. It could be a numpy array or a simple list.
# Could also be used to create new columns
df1.loc[1:3, 'col3'] = ['Unknown0'] * 3
df1

col1          col2      col3
0  Item0          Gold         1
1  Item0  Bronze again  Unknown0
2  Item1          Gold  Unknown0
3  Item1        Silver  Unknown0

In [38]:
# Equivalent to the previous
df1.col3 = ['Unknown1'] * len(df1) 
df1

# 위와 동일하게 동작하는 코드
# df1.loc[:, 'col3'] = ['Unknown2'] * len(df1)

col1          col2      col3
0  Item0          Gold  Unknown1
1  Item0  Bronze again  Unknown1
2  Item1          Gold  Unknown1
3  Item1        Silver  Unknown1

In [39]:
def f(x):
    return x + ' New Column';

# Uses the unary function f to create a new column based on an existing one
df1.col4 = f(df1.col3) 
df1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """


col1          col2      col3
0  Item0          Gold  Unknown1
1  Item0  Bronze again  Unknown1
2  Item1          Gold  Unknown1
3  Item1        Silver  Unknown1

In [40]:
def g(x, y):
    return x + '_' + y

# Uses the 2-arg function g to create a new column based on 2 existing columns
df1.col4 = g(df1.col3, df1.col2)
df1

col1          col2      col3
0  Item0          Gold  Unknown1
1  Item0  Bronze again  Unknown1
2  Item1          Gold  Unknown1
3  Item1        Silver  Unknown1

In [43]:
df = pd.read_csv('./Graduate_apply.csv', sep=',', skipinitialspace=True, engine='python')
print(df.head())
print("------")

# 특정 칼럼의 Dummy Variable을 얻기
df_rank = pd.get_dummies(df['rank'])
print(df_rank.head())
print("------")

# Dummy 데이터를 원래 데이터와 합치기
df_new = pd.concat([df, df_rank], axis=1)
print(df_new.head())
print("------")

# 특정 칼럼 제거하기
df_new.drop('rank', axis=1, inplace=True)
print(df_new.head())
print("------")

# 여러 칼럼 동시 제거하기
df_new.drop(['gre', 'gpa'], axis=1, inplace=True)
print(df_new.head())
print("------")


   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4
------
   1  2  3  4
0  0  0  1  0
1  0  0  1  0
2  1  0  0  0
3  0  0  0  1
4  0  0  0  1
------
   admit  gre   gpa  rank  1  2  3  4
0      0  380  3.61     3  0  0  1  0
1      1  660  3.67     3  0  0  1  0
2      1  800  4.00     1  1  0  0  0
3      1  640  3.19     4  0  0  0  1
4      0  520  2.93     4  0  0  0  1
------
   admit  gre   gpa  1  2  3  4
0      0  380  3.61  0  0  1  0
1      1  660  3.67  0  0  1  0
2      1  800  4.00  1  0  0  0
3      1  640  3.19  0  0  0  1
4      0  520  2.93  0  0  0  1
------
   admit  1  2  3  4
0      0  0  0  1  0
1      1  0  0  1  0
2      1  1  0  0  0
3      1  0  0  0  1
4      0  0  0  0  1
------


## 06. Group by, Join, Rolling

In [0]:
import pandas as pd

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/RayleighKim/Example_datasets/master/Graduate_apply.csv')

In [165]:
print(df.shape)
df.head(3)

(400, 4)


admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1

[고군분투의 흔적](https://www.facebook.com/photo.php?fbid=1939114629501924&set=a.1046527102094019&type=3)

### 06-1. Group by

일단 단순한 수준에서 겪어보자

In [167]:
df.groupby(by=['rank'], as_index = False)['gre'].mean()

rank         gre
0     1  611.803279
1     2  596.026490
2     3  574.876033
3     4  570.149254

In [63]:
df.groupby(by = ['rank', 'admit'], as_index=False)['gre', 'gpa'].mean()

rank  admit         gre       gpa
0     1      0  582.857143  3.345714
1     1      1  636.363636  3.544242
2     2      0  586.597938  3.316598
3     2      1  612.962963  3.442593
4     3      0  562.365591  3.402258
5     3      1  616.428571  3.534643
6     4      0  562.909091  3.291455
7     4      1  603.333333  3.441667

In [140]:
df.groupby(by = ['rank', 'admit'], as_index=False)['gre', 'gpa'].std()

rank  admit         gre       gpa
0  1.000000    0.0  126.574737  0.375445
1  1.000000    1.0  110.618098  0.385511
2  1.414214    0.0  103.066388  0.377927
3  1.414214    1.0  112.746663  0.361653
4  1.732051    0.0  124.650798  0.379434
5  1.732051    1.0   99.785484  0.399244
6  2.000000    0.0  116.327646  0.369767
7  2.000000    1.0  114.680056  0.297286

In [77]:
df.groupby(by = ['rank', 'admit'], as_index=False).count()

rank  admit  gre  gpa
0     1      0   28   28
1     1      1   33   33
2     2      0   97   97
3     2      1   54   54
4     3      0   93   93
5     3      1   28   28
6     4      0   55   55
7     4      1   12   12

In [79]:
df.groupby(by = ['rank', 'admit'], as_index=False)['gre'].count()

rank  admit  gre
0     1      0   28
1     1      1   33
2     2      0   97
3     2      1   54
4     3      0   93
5     3      1   28
6     4      0   55
7     4      1   12

이름들이 조금 이상하다. 컬럼이름을 바꾸어보자

In [83]:
df_by_rank = df.groupby(by = ['rank'], as_index=False)['gre'].mean()
df_by_rank.head()

rank         gre
0     1  611.803279
1     2  596.026490
2     3  574.876033
3     4  570.149254

In [0]:
if 'gre' in df_by_rank.columns :
    df_by_rank.rename(columns={'gre':'gre_mean'}, inplace = True)

In [89]:
df_by_rank.head()

rank    gre_mean
0     1  611.803279
1     2  596.026490
2     3  574.876033
3     4  570.149254

실습해봅시다!

rank, admit 기준으로 gre의 최대값을 출력하시오.

.max()를 사용하면 됩니다.

In [206]:
## Your Code



rank  admit  gre
0     1      0  800
1     1      1  800
2     2      0  800
3     2      1  800
4     3      0  800
5     3      1  800
6     4      0  800
7     4      1  780

### 06-2 Join

In [93]:
mean_by_rank = df.groupby(by = ['rank'], as_index=False)['gre', 'gpa'].mean()
mean_by_rank.rename(columns = {'gre':'gre_mean', 'gpa':'gpa_mean'}, inplace = True)
mean_by_rank

rank    gre_mean  gpa_mean
0     1  611.803279  3.453115
1     2  596.026490  3.361656
2     3  574.876033  3.432893
3     4  570.149254  3.318358

In [175]:
'''
pandas,  ver0.22.0 기준으로 망가져 있는 기능.
rank가 미쳐보이지만 놀랍게도, 값들은 정상입니다.
'''
std_by_rank = df.groupby(by = ['rank'], as_index=False)['gre', 'gpa'].std()
std_by_rank.rename(columns = {'gre':'gre_std', 'gpa':'gpa_std'}, inplace = True)
std_by_rank

rank     gre_std   gpa_std
0  1.000000  120.242924  0.390698
1  1.414214  107.008283  0.375893
2  1.732051  121.148089  0.386502
3  2.000000  116.221999  0.360507

pandas ver0.22.0 기준으로 망가져 있는 기능을 우회하여 사용하는 가장 빠른 방법은 다음과 같습니다.

In [177]:
std_by_rank['rank'] = mean_by_rank['rank']
std_by_rank

rank     gre_std   gpa_std
0     1  120.242924  0.390698
1     2  107.008283  0.375893
2     3  121.148089  0.386502
3     4  116.221999  0.360507

판다스에서 join은 굉장히 간단합니다.

자동으로 key를 잡아줍니다!

다만, 자동으로 inner join을 합니다.

In [180]:
pd.merge(mean_by_rank, std_by_rank)

rank    gre_mean  gpa_mean     gre_std   gpa_std
0     1  611.803279  3.453115  120.242924  0.390698
1     2  596.026490  3.361656  107.008283  0.375893
2     3  574.876033  3.432893  121.148089  0.386502
3     4  570.149254  3.318358  116.221999  0.360507

In [183]:
pd.merge(mean_by_rank, std_by_rank, on = 'rank', how = 'outer')

rank    gre_mean  gpa_mean     gre_std   gpa_std
0     1  611.803279  3.453115  120.242924  0.390698
1     2  596.026490  3.361656  107.008283  0.375893
2     3  574.876033  3.432893  121.148089  0.386502
3     4  570.149254  3.318358  116.221999  0.360507

multiple key에 대해서도 자동으로 join이 됩니다!

In [185]:
mean_by_rank2 = df.groupby(by = ['rank', 'admit'], as_index=False)['gre', 'gpa'].mean()
mean_by_rank2.rename(columns = {'gre':'gre_mean', 'gpa':'gpa_mean'}, inplace = True)
mean_by_rank2

rank  admit    gre_mean  gpa_mean
0     1      0  582.857143  3.345714
1     1      1  636.363636  3.544242
2     2      0  586.597938  3.316598
3     2      1  612.962963  3.442593
4     3      0  562.365591  3.402258
5     3      1  616.428571  3.534643
6     4      0  562.909091  3.291455
7     4      1  603.333333  3.441667

In [187]:
std_by_rank2 = df.groupby(by = ['rank','admit'], as_index=False)['gre', 'gpa'].std()
std_by_rank2.rename(columns = {'gre':'gre_std', 'gpa':'gpa_std'}, inplace = True)
std_by_rank2['rank'] = mean_by_rank2['rank']
std_by_rank2

rank  admit     gre_std   gpa_std
0     1    0.0  126.574737  0.375445
1     1    1.0  110.618098  0.385511
2     2    0.0  103.066388  0.377927
3     2    1.0  112.746663  0.361653
4     3    0.0  124.650798  0.379434
5     3    1.0   99.785484  0.399244
6     4    0.0  116.327646  0.369767
7     4    1.0  114.680056  0.297286

In [189]:
pd.merge(mean_by_rank2,std_by_rank2)

rank admit    gre_mean  gpa_mean     gre_std   gpa_std
0     1     0  582.857143  3.345714  126.574737  0.375445
1     1     1  636.363636  3.544242  110.618098  0.385511
2     2     0  586.597938  3.316598  103.066388  0.377927
3     2     1  612.962963  3.442593  112.746663  0.361653
4     3     0  562.365591  3.402258  124.650798  0.379434
5     3     1  616.428571  3.534643   99.785484  0.399244
6     4     0  562.909091  3.291455  116.327646  0.369767
7     4     1  603.333333  3.441667  114.680056  0.297286

실습해봅시다!

rank, admit 기준으로 gre의 최소값을 담는 dataframe을 만들어

다음의 데이터 프레임(df_to_merge)와 join 하시오.

In [207]:
df_to_merge = pd.merge(mean_by_rank2, std_by_rank2)
df_to_merge.head()

rank admit    gre_mean  gpa_mean     gre_std   gpa_std
0     1     0  582.857143  3.345714  126.574737  0.375445
1     1     1  636.363636  3.544242  110.618098  0.385511
2     2     0  586.597938  3.316598  103.066388  0.377927
3     2     1  612.962963  3.442593  112.746663  0.361653
4     3     0  562.365591  3.402258  124.650798  0.379434

In [208]:
df_mingre = df.groupby(by = ['rank','admit'], as_index=False)['gre'].min()
df_mingre

rank  admit  gre
0     1      0  340
1     1      1  460
2     2      0  380
3     2      1  300
4     3      0  220
5     3      1  460
6     4      0  300
7     4      1  400

In [209]:
### Your Code here

rank admit    gre_mean  gpa_mean     gre_std   gpa_std  gre
0     1     0  582.857143  3.345714  126.574737  0.375445  340
1     1     1  636.363636  3.544242  110.618098  0.385511  460
2     2     0  586.597938  3.316598  103.066388  0.377927  380
3     2     1  612.962963  3.442593  112.746663  0.361653  300
4     3     0  562.365591  3.402258  124.650798  0.379434  220
5     3     1  616.428571  3.534643   99.785484  0.399244  460
6     4     0  562.909091  3.291455  116.327646  0.369767  300
7     4     1  603.333333  3.441667  114.680056  0.297286  400

### 06-3 Rolling


In [0]:
import pandas as pd

In [191]:
stock = pd.read_csv('https://raw.githubusercontent.com/RayleighKim/Example_datasets/master/Stock_Edwards_Lifesciences_corporation.csv')
stock.head()

Date      Open      High       Low     Close  Adj_Close   Volume
0  2000/3/27  3.812500  4.156250  3.812500  4.125000   4.125000  3675600
1  2000/3/28  4.125000  4.125000  4.000000  4.015625   4.015625  1077600
2  2000/3/29  4.000000  4.031250  3.953125  4.000000   4.000000   437200
3  2000/3/30  4.000000  4.000000  3.843750  3.843750   3.843750  1883600
4  2000/3/31  3.734375  3.734375  3.390625  3.390625   3.390625  7931600

Date 와 Close 가격만을 남겨 보죠.

In [194]:
stock = stock[['Date', 'Close']]
stock.head()

Date     Close
0  2000/3/27  4.125000
1  2000/3/28  4.015625
2  2000/3/29  4.000000
3  2000/3/30  3.843750
4  2000/3/31  3.390625

기준일 포함하여 과거 3일의 평균을 데이터 프레임에 붙여봅시다.

In [196]:
stock['Close_MA_3'] = stock['Close'].rolling(3).mean()
stock.head(10)

Date     Close  Close_MA_3
0  2000/3/27  4.125000         NaN
1  2000/3/28  4.015625         NaN
2  2000/3/29  4.000000    4.046875
3  2000/3/30  3.843750    3.953125
4  2000/3/31  3.390625    3.744792
5   2000/4/3  3.437500    3.557292
6   2000/4/4  3.500000    3.442708
7   2000/4/5  3.484375    3.473958
8   2000/4/6  3.578125    3.520833
9   2000/4/7  3.609375    3.557292

기준일 포함하여 과거 3일 중 최대값은 어떨까요?

In [197]:
stock['Close_MM_3'] = stock['Close'].rolling(3).max()
stock.head(10)

Date     Close  Close_MA_3  Close_MM_3
0  2000/3/27  4.125000         NaN         NaN
1  2000/3/28  4.015625         NaN         NaN
2  2000/3/29  4.000000    4.046875    4.125000
3  2000/3/30  3.843750    3.953125    4.015625
4  2000/3/31  3.390625    3.744792    4.000000
5   2000/4/3  3.437500    3.557292    3.843750
6   2000/4/4  3.500000    3.442708    3.500000
7   2000/4/5  3.484375    3.473958    3.500000
8   2000/4/6  3.578125    3.520833    3.578125
9   2000/4/7  3.609375    3.557292    3.609375

기준일을 포함하지 않은, 과거 3일의 평균을 붙인다면?

In [201]:
stock['Close_MA_3_lag1'] = stock['Close_MA_3'].shift()
stock.head()

Date     Close  Close_MA_3  Close_MM_3  Close_MA_3_lag1
0  2000/3/27  4.125000         NaN         NaN              NaN
1  2000/3/28  4.015625         NaN         NaN              NaN
2  2000/3/29  4.000000    4.046875    4.125000              NaN
3  2000/3/30  3.843750    3.953125    4.015625         4.046875
4  2000/3/31  3.390625    3.744792    4.000000         3.953125

실습!!

stock 옆에, 과거 4일의 표준편차를 붙이시오!

In [204]:
stock['Close_MS_3'] = ## Your Code
    
stock.head()

SyntaxError: ignored